spring:
  ### 静态资源 ###
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/
    cache:
      period: 3600
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://101.132.47.22:3306/seckill?useSSL=false
    username: root
    password: WANGpc@0303
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 1000
      initial-size: 20
      max-wait: 30000
      min-idle: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 118.24.105.155
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.5

### mybatis
mybatis:
  type-aliases-package: com.imooc.seckill.entity
  mapper-locations: classpath:com/imooc/seckill/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 60

### redis
redis:
  host: 101.132.47.22
  port: 6379
  timeout: 100000
  password: wang1991
  max-active: 10000
  max-idle: 2000
  max-wait: 100000
server:
  port: 80
