spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://101.132.47.22:3306/seckill?useSSL=false
    username: root
    password: WANGpc@0303
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 1000
      initial-size: 100
      max-wait: 60000
      min-idle: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      driver-class-name: com.mysql.jdbc.Driver



### mybatis
mybatis:
  type-aliases-package: com.imooc.seckill.entity
  mapper-locations: classpath:com/imooc/seckill/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

### redis
redis:
  host: 101.132.47.22
  port: 6379
  timeout: 30
  password: wang1991
  max-active: 1000
  max-idle: 500
  max-wait: 500
